### ISSUE TITLE
Use generic targets rather than local mock proxy

### ISSUE THREAD

**Issue by kurtkanaskie** [kurtkanaskie/pingstatus-v1-x#2]
Don't use a local pingstatus-mock proxy or provide that proxy and install first.

**Comment by ma198307** [comment]
I am trying to replicate this in apigeeX with hello-world api , api deployment works fine but product and app creation fails.
I have created a code repo and placed apiproxy and resource folder in the repo at root level  without the parent folder. 
 --- apigee-config-maven-plugin:2.1.2:apps (default-cli) @ hello-world ---
[WARNING] The artifact xml-apis:xml-apis:jar:2.0.2 has been relocated to xml-apis:xml-apis:jar:1.0.b2
[INFO] ************************************************************************
[INFO] Apigee App
[INFO] ************************************************************************
[INFO] Config file org/developerApps.json not found.
[INFO] No developers apps found.

The file resources/edge/org/developerApps.json exist .
